// Common beginner greetings and polite expressions, including everyday variants.
// Original supplemental vocabulary, CC BY-SA 4.0 (see data/README.md).
export const greetings = [
  ['こんにちは', 'konnichiwa', 'hello; good afternoon'],
  ['おはよう', 'ohayou', 'good morning (casual)'],
  ['おはようございます', 'ohayou gozaimasu', 'good morning (polite)'],
  ['こんばんは', 'konbanwa', 'good evening'],
  ['おやすみ', 'oyasumi', 'good night (casual)'],
  ['おやすみなさい', 'oyasuminasai', 'good night (polite)'],
  ['さようなら', 'sayounara', 'goodbye'],
  ['さよなら', 'sayonara', 'goodbye (short form)'],
  ['じゃあね', 'jaa ne', 'see you; bye (casual)'],
  ['またね', 'mata ne', 'see you again (casual)'],
  ['またあした', 'mata ashita', 'see you tomorrow'],
  ['はじめまして', 'hajimemashite', 'nice to meet you (first meeting)'],
  ['よろしくおねがいします', 'yoroshiku onegai shimasu', 'pleased to meet you; I look forward to working with you'],
  ['おげんきですか', 'ogenki desu ka', 'how are you?'],
  ['おひさしぶりです', 'ohisashiburi desu', 'long time no see'],
  ['ただいま', 'tadaima', 'I am home'],
  ['おかえり', 'okaeri', 'welcome home (casual)'],
  ['おかえりなさい', 'okaerinasai', 'welcome home (polite)'],
  ['いってきます', 'ittekimasu', 'I am leaving; see you when I get back'],
  ['いってらっしゃい', 'itterasshai', 'take care; see you when you get back'],
  ['いらっしゃいませ', 'irasshaimase', 'welcome (to a shop or restaurant)'],
  ['ようこそ', 'youkoso', 'welcome'],
  ['ありがとう', 'arigatou', 'thank you (casual)'],
  ['ありがとうございます', 'arigatou gozaimasu', 'thank you (polite)'],
  ['どうもありがとうございます', 'doumo arigatou gozaimasu', 'thank you very much'],
  ['どういたしまして', 'dou itashimashite', 'you are welcome'],
  ['すみません', 'sumimasen', 'excuse me; I am sorry'],
  ['ごめんね', 'gomen ne', 'sorry (casual)'],
  ['ごめんなさい', 'gomennasai', 'I am sorry'],
  ['おねがいします', 'onegai shimasu', 'please (when making a request)'],
  ['いただきます', 'itadakimasu', 'said before eating; thank you for the meal'],
  ['ごちそうさまでした', 'gochisousama deshita', 'thank you for the meal (after eating)'],
  ['おめでとう', 'omedetou', 'congratulations (casual)'],
  ['おめでとうございます', 'omedetou gozaimasu', 'congratulations (polite)'],
  ['おつかれさまです', 'otsukaresama desu', 'thank you for your work; greeting to a colleague'],
  ['しつれいします', 'shitsurei shimasu', 'excuse me (when entering, leaving, or interrupting)'],
] as const;
